name: complete-checking

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check CLI functional
        run: chmod +x ./scylla-perf |
              ./scylla-perf  -h
  compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "docker-compose.yml"
      - name: Check Docker Compose functional
        run: docker compose up -d
  run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ScribeMD/rootless-docker@0.2.2
      - name: Use Docker in rootless mode.
        run: |
            docker run --name some-scylla --hostname some-scylla -p 9042:9042 -p 19042:19042 -d scylladb/scylla --smp 1
            sleep 3
            chmod +x ./scylla-perf
            ./scylla-perf 2 --ci

